# Generated by Django 2.0.9 on 2018-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20181210_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
