# Generated by Django 2.0.9 on 2018-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
