# Generated by Django 2.0.9 on 2018-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20181210_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
